language: php

php:
  - 7.3
  - 7.4

services:
  - postgresql

before_script:
  - psql -c 'create database symfony_test;' -U postgres
  - phpenv config-rm xdebug.ini
  - cd back-end
  - composer self-update
  - composer install
  - APP_ENV=test bin/console doctrine:schema:create -q
  - APP_ENV=test bin/console doctrine:fixtures:load -q --purge-with-truncate

script:
  - phpunit
