application:
    build: ../back-end
    ports:
      - 9000:9000
    volumes:
        - ../back-end:/var/www
        - ../back-end/web:/var/www/html
#        - ./php-fpm/php.ini:/etc/php5/fpm/php.ini
#        - ./php-fpm/php.ini:/etc/php5/cli/php.ini
        - ./php-fpm/symfony.pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
        - /var/www/app/cache
        - /var/www/app/logs
    links:
      - db

client:
    build: ../front-end
    ports:
      - 3000:3000
    volumes:
        - ../front-end:/var/www/angular
    links:
      - nginx-back

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony

nginx-front:
    image: nginx
    ports:
        - 80:80
    links:
        - client
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/express.conf:/etc/nginx/conf.d/default.conf

nginx-back:
    image: nginx
    ports:
        - 8080:8080
    links:
        - application
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
