application:
    build: ../back-end
    volumes:
        - ../back-end:/var/www
        # - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        # - ./php-fpm/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        # - ./php-fpm/symfony.pool.conf:/usr/local/etc/php-fpm.d/symfony.pool.conf
    links:
        - database

client:
    build: ../front-end
    volumes:
      - '../front-end:/app'
    links:
      - nginx-back

database:
    image: postgres:10
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: symfony_test

nginx-front:
    image: nginx
    ports:
        - 8080:8080
    links:
        - client
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/angular.conf:/etc/nginx/conf.d/default.conf

nginx-back:
    image: nginx
    ports:
        - 8000:8000
    links:
        - application
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
