application:
    build: ../back-end
    ports:
      - 9000:9000
    volumes:
        - ../back-end:/var/www
        - ../back-end/web:/var/www/html
        - ./php-fpm/symfony.ini:/etc/php5/fpm/conf.d/symfony.ini
        - ./php-fpm/symfony.ini:/etc/php5/cli/conf.d/symfony.ini
        - ./php-fpm/symfony.pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
        - /var/www/app/cache
        - /var/www/app/logs
    links:
      - db
client:
    build: ../front-end
    volumes:
        - ../front-end:/var/www/angular
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
nginx:
    image: nginx
    ports:
        - 80:80
        - 8080:8080
    links:
        - application
    volumes_from:
        - client
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
